/**
 * AI Agent for Automatic Unsplash Image Extraction
 * 
 * This agent automatically searches Unsplash for product images and extracts
 * the direct image URLs to populate the product image database.
 */

// Note: Install axios with: npm install axios
// import axios from 'axios';

// Unsplash API configuration
const UNSPLASH_ACCESS_KEY = process.env.UNSPLASH_ACCESS_KEY || 'YOUR_UNSPLASH_ACCESS_KEY';
const UNSPLASH_API_BASE = 'https://api.unsplash.com';

interface UnsplashImage {
  id: string;
  urls: {
    raw: string;
    full: string;
    regular: string;
    small: string;
    thumb: string;
  };
  alt_description: string;
  description: string;
}

interface ProductImageMapping {
  productName: string;
  imageUrl: string;
  altText: string;
}

/**
 * AI Agent Class for Unsplash Image Extraction
 */
class UnsplashImageAgent {
  private accessKey: string;
  private rateLimitDelay: number = 1000; // 1 second between requests

  constructor(accessKey: string) {
    this.accessKey = accessKey;
  }

  /**
   * Search Unsplash for a product image
   */
  async searchProductImage(productName: string, category?: string): Promise<UnsplashImage | null> {
    try {
      // Construct search query with product name and category
      const searchQuery = category ? `${productName} ${category}` : productName;

      const response = await fetch(`${UNSPLASH_API_BASE}/search/photos?query=${encodeURIComponent(searchQuery)}&per_page=1&orientation=squarish`, {
        headers: {
          'Authorization': `Client-ID ${this.accessKey}`,
        },
      });

      const data = await response.json();

      if (data.results && data.results.length > 0) {
        return data.results[0];
      }

      return null;
    } catch (error) {
      console.error(`Error searching for ${productName}:`, error);
      return null;
    }
  }

  /**
   * Generate optimized image URL with specific dimensions
   */
  generateOptimizedUrl(imageId: string, width: number = 600, height: number = 600): string {
    return `https://images.unsplash.com/photo-${imageId}?w=${width}&h=${height}&fit=crop&auto=format`;
  }

  /**
   * Extract image URL from Unsplash photo object
   */
  extractImageUrl(image: UnsplashImage, optimized: boolean = true): string {
    if (optimized) {
      // Extract photo ID from URL
      const photoId = image.id;
      return `https://images.unsplash.com/photo-${photoId}?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0`;
    }
    return image.urls.regular;
  }

  /**
   * Process a list of products and fetch images for each
   */
  async processProductList(products: string[], category?: string): Promise<ProductImageMapping[]> {
    const mappings: ProductImageMapping[] = [];

    for (const product of products) {
      console.log(`Searching for image: ${product}...`);

      const image = await this.searchProductImage(product, category);

      if (image) {
        const imageUrl = this.extractImageUrl(image);
        mappings.push({
          productName: product,
          imageUrl: imageUrl,
          altText: image.alt_description || product,
        });

        console.log(`✓ Found image for ${product}`);
      } else {
        console.log(`✗ No image found for ${product}`);
      }

      // Rate limiting - wait before next request
      await this.delay(this.rateLimitDelay);
    }

    return mappings;
  }

  /**
   * Generate TypeScript code for productImages.ts
   */
  generateProductImageCode(mappings: ProductImageMapping[]): string {
    let code = '// Auto-generated by UnsplashImageAgent\n';
    code += 'const PRODUCT_IMAGE_DATABASE: ProductImageMap = {\n';

    mappings.forEach((mapping) => {
      code += `  '${mapping.productName}': '${mapping.imageUrl}',\n`;
    });

    code += '};\n';
    return code;
  }

  /**
   * Verify if image URL is accessible (not 404)
   */
  async verifyImageUrl(url: string): Promise<boolean> {
    try {
      const response = await fetch(url, { method: 'HEAD' });
      return response.status === 200;
    } catch (error) {
      return false;
    }
  }

  /**
   * Batch verify multiple image URLs
   */
  async verifyImageBatch(urls: string[]): Promise<Map<string, boolean>> {
    const results = new Map<string, boolean>();

    for (const url of urls) {
      const isValid = await this.verifyImageUrl(url);
      results.set(url, isValid);
      await this.delay(100); // Small delay between verifications
    }

    return results;
  }

  /**
   * Smart image search with fallback strategies
   */
  async smartSearch(productName: string, category?: string): Promise<string | null> {
    // Strategy 1: Search with product name + category
    if (category) {
      const image1 = await this.searchProductImage(productName, category);
      if (image1) return this.extractImageUrl(image1);
    }

    // Strategy 2: Search with just product name
    const image2 = await this.searchProductImage(productName);
    if (image2) return this.extractImageUrl(image2);

    // Strategy 3: Search with generic category terms
    if (category) {
      const image3 = await this.searchProductImage(category);
      if (image3) return this.extractImageUrl(image3);
    }

    return null;
  }

  /**
   * Utility delay function
   */
  private delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
}

/**
 * Example usage function
 */
async function demonstrateAgent() {
  // Initialize the agent
  const agent = new UnsplashImageAgent(UNSPLASH_ACCESS_KEY);

  // Example 1: Search for a single product
  console.log('=== Example 1: Single Product Search ===');
  const laptopImage = await agent.searchProductImage('laptop', 'electronics');
  if (laptopImage) {
    const url = agent.extractImageUrl(laptopImage);
    console.log(`Laptop image URL: ${url}`);
  }

  // Example 2: Process multiple products
  console.log('\n=== Example 2: Batch Processing ===');
  const products = ['football', 'cricket bat', 'tennis racket', 'basketball'];
  const mappings = await agent.processProductList(products, 'sports');
  
  // Example 3: Generate code output
  console.log('\n=== Example 3: Generated Code ===');
  const generatedCode = agent.generateProductImageCode(mappings);
  console.log(generatedCode);

  // Example 4: Verify existing URLs
  console.log('\n=== Example 4: URL Verification ===');
  const urlsToVerify = [
    'https://images.unsplash.com/photo-1614632537197-38a17061829d',
    'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1',
  ];
  const verificationResults = await agent.verifyImageBatch(urlsToVerify);
  verificationResults.forEach((isValid, url) => {
    console.log(`${url}: ${isValid ? '✓ Valid' : '✗ Broken'}`);
  });

  // Example 5: Smart search with fallbacks
  console.log('\n=== Example 5: Smart Search ===');
  const smartUrl = await agent.smartSearch('yoga mat', 'fitness');
  console.log(`Smart search result: ${smartUrl}`);
}

/**
 * Advanced: Read CSV and auto-populate images
 */
async function autoPopulateFromCSV(csvPath: string) {
  const fs = require('fs');
  const csv = require('csv-parser');
  
  const agent = new UnsplashImageAgent(UNSPLASH_ACCESS_KEY);
  const productSet = new Set<string>();
  const mappings: ProductImageMapping[] = [];

  // Read unique products from CSV
  return new Promise((resolve, reject) => {
    fs.createReadStream(csvPath)
      .pipe(csv())
      .on('data', (row: any) => {
        if (row.product_name) {
          productSet.add(row.product_name.toLowerCase());
        }
      })
      .on('end', async () => {
        console.log(`Found ${productSet.size} unique products`);
        
        // Process each unique product
        for (const product of Array.from(productSet)) {
          const imageUrl = await agent.smartSearch(product);
          if (imageUrl) {
            mappings.push({
              productName: product,
              imageUrl: imageUrl,
              altText: product,
            });
          }
        }

        console.log(`Successfully mapped ${mappings.length} products`);
        resolve(mappings);
      })
      .on('error', reject);
  });
}

// Export for use in other modules
export {
  UnsplashImageAgent,
  demonstrateAgent,
  autoPopulateFromCSV,
};

export type { ProductImageMapping };

// If run directly, execute demonstration
if (require.main === module) {
  demonstrateAgent()
    .then(() => console.log('\n✓ Agent demonstration complete'))
    .catch((error) => console.error('Error:', error));
}
